package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	model1 "backend-productos/graph/model"
	"backend-productos/internal/domain/model"
	"context"

	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *categoriaResolver) ID(ctx context.Context, obj *model.Categoria) (string, error) {
	return obj.ID.String(), nil
}

// Productos is the resolver for the productos field.
func (r *categoriaResolver) Productos(ctx context.Context, obj *model.Categoria) ([]*model.Producto, error) {
	productos := make([]*model.Producto, 0, len(obj.ProductoIDs))
	for _, pid := range obj.ProductoIDs {
		id, err := uuid.Parse(pid)
		if err != nil {
			continue
		}
		p, err := r.ProductoService.GetByID(ctx, id)
		if err != nil {
			continue
		}
		productos = append(productos, p)
	}
	return productos, nil
}

// ID is the resolver for the id field.
func (r *inventarioResolver) ID(ctx context.Context, obj *model.Inventario) (string, error) {
	return obj.ID.String(), nil
}

// CrearProducto is the resolver for the crearProducto field.
func (r *mutationResolver) CrearProducto(ctx context.Context, input model1.CreateProductoInput) (*model.Producto, error) {
	p := &model.Producto{
		Nombre: input.Nombre,
		Precio: input.Precio,
	}
	if input.Descripcion != nil {
		p.Descripcion = *input.Descripcion
	}

	if err := r.ProductoService.Create(ctx, p); err != nil {
		return nil, err
	}
	return p, nil
}

// ActualizarProducto is the resolver for the actualizarProducto field.
func (r *mutationResolver) ActualizarProducto(ctx context.Context, id string, input model1.UpdateProductoInput) (*model.Producto, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	update := &model.Producto{}
	if input.Nombre != nil {
		update.Nombre = *input.Nombre
	}
	if input.Descripcion != nil {
		update.Descripcion = *input.Descripcion
	}
	if input.Precio != nil {
		update.Precio = *input.Precio
	}

	return r.ProductoService.Update(ctx, uid, update)
}

// EliminarProducto is the resolver for the eliminarProducto field.
func (r *mutationResolver) EliminarProducto(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}

	if err := r.ProductoService.Delete(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// CrearCategoria is the resolver for the crearCategoria field.
func (r *mutationResolver) CrearCategoria(ctx context.Context, input model1.CreateCategoriaInput) (*model.Categoria, error) {
	c := &model.Categoria{
		Nombre:      input.Nombre,
		ProductoIDs: input.ProductoIds,
	}
	if input.Descripcion != nil {
		c.Descripcion = *input.Descripcion
	}

	if err := r.CategoriaService.Create(ctx, c); err != nil {
		return nil, err
	}
	return c, nil
}

// ActualizarCategoria is the resolver for the actualizarCategoria field.
func (r *mutationResolver) ActualizarCategoria(ctx context.Context, id string, input model1.UpdateCategoriaInput) (*model.Categoria, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	update := &model.Categoria{}
	if input.Nombre != nil {
		update.Nombre = *input.Nombre
	}
	if input.Descripcion != nil {
		update.Descripcion = *input.Descripcion
	}
	if input.ProductoIds != nil {
		update.ProductoIDs = input.ProductoIds
	}

	return r.CategoriaService.Update(ctx, uid, update)
}

// EliminarCategoria is the resolver for the eliminarCategoria field.
func (r *mutationResolver) EliminarCategoria(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}

	if err := r.CategoriaService.Delete(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// CrearInventario is the resolver for the crearInventario field.
func (r *mutationResolver) CrearInventario(ctx context.Context, input model1.CreateInventarioInput) (*model.Inventario, error) {
	i := &model.Inventario{
		ProductoID: input.ProductoID,
		Cantidad:   input.Cantidad,
		Almacen:    input.Almacen,
	}

	if err := r.InventarioService.Create(ctx, i); err != nil {
		return nil, err
	}
	return i, nil
}

// ActualizarInventario is the resolver for the actualizarInventario field.
func (r *mutationResolver) ActualizarInventario(ctx context.Context, id string, input model1.UpdateInventarioInput) (*model.Inventario, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	update := &model.Inventario{}
	if input.Cantidad != nil {
		update.Cantidad = *input.Cantidad
	}
	if input.Almacen != nil {
		update.Almacen = *input.Almacen
	}

	return r.InventarioService.Update(ctx, uid, update)
}

// EliminarInventario is the resolver for the eliminarInventario field.
func (r *mutationResolver) EliminarInventario(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}

	if err := r.InventarioService.Delete(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// ID is the resolver for the id field.
func (r *productoResolver) ID(ctx context.Context, obj *model.Producto) (string, error) {
	return obj.ID.String(), nil
}

// Categoria is the resolver for the categoria field.
func (r *productoResolver) Categoria(ctx context.Context, obj *model.Producto) (*model.Categoria, error) {
	categorias, err := r.CategoriaService.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	productoID := obj.ID.String()
	for i := range categorias {
		for _, pid := range categorias[i].ProductoIDs {
			if pid == productoID {
				return &categorias[i], nil
			}
		}
	}
	return nil, nil
}

// Inventario is the resolver for the inventario field.
func (r *productoResolver) Inventario(ctx context.Context, obj *model.Producto) (*model.Inventario, error) {
	inv, err := r.InventarioService.GetByProductoID(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return inv, nil
}

// Productos is the resolver for the productos field.
func (r *queryResolver) Productos(ctx context.Context, page *int, limit *int) ([]*model.Producto, error) {
	p := 1
	l := 20
	if page != nil {
		p = *page
	}
	if limit != nil {
		l = *limit
	}

	productos, err := r.ProductoService.GetAll(ctx, p, l)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Producto, len(productos))
	for i := range productos {
		result[i] = &productos[i]
	}
	return result, nil
}

// Producto is the resolver for the producto field.
func (r *queryResolver) Producto(ctx context.Context, id string) (*model.Producto, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	return r.ProductoService.GetByID(ctx, uid)
}

// Categorias is the resolver for the categorias field.
func (r *queryResolver) Categorias(ctx context.Context) ([]*model.Categoria, error) {
	categorias, err := r.CategoriaService.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Categoria, len(categorias))
	for i := range categorias {
		result[i] = &categorias[i]
	}
	return result, nil
}

// Categoria is the resolver for the categoria field.
func (r *queryResolver) Categoria(ctx context.Context, id string) (*model.Categoria, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	return r.CategoriaService.GetByID(ctx, uid)
}

// Inventarios is the resolver for the inventarios field.
func (r *queryResolver) Inventarios(ctx context.Context) ([]*model.Inventario, error) {
	inventarios, err := r.InventarioService.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Inventario, len(inventarios))
	for i := range inventarios {
		result[i] = &inventarios[i]
	}
	return result, nil
}

// Inventario is the resolver for the inventario field.
func (r *queryResolver) Inventario(ctx context.Context, id string) (*model.Inventario, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	return r.InventarioService.GetByID(ctx, uid)
}

// InventarioByProducto is the resolver for the inventarioByProducto field.
func (r *queryResolver) InventarioByProducto(ctx context.Context, productoID string) (*model.Inventario, error) {
	return r.InventarioService.GetByProductoID(ctx, productoID)
}

// Categoria returns CategoriaResolver implementation.
func (r *Resolver) Categoria() CategoriaResolver { return &categoriaResolver{r} }

// Inventario returns InventarioResolver implementation.
func (r *Resolver) Inventario() InventarioResolver { return &inventarioResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Producto returns ProductoResolver implementation.
func (r *Resolver) Producto() ProductoResolver { return &productoResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type categoriaResolver struct{ *Resolver }
type inventarioResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type productoResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
