// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCategoriaInput struct {
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	ProductoIds []string `json:"productoIds,omitempty"`
}

type CreateInventarioInput struct {
	ProductoID string `json:"productoId"`
	Cantidad   int    `json:"cantidad"`
	Almacen    string `json:"almacen"`
}

type CreateProductoInput struct {
	Nombre      string  `json:"nombre"`
	Descripcion *string `json:"descripcion,omitempty"`
	Precio      float64 `json:"precio"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateCategoriaInput struct {
	Nombre      *string  `json:"nombre,omitempty"`
	Descripcion *string  `json:"descripcion,omitempty"`
	ProductoIds []string `json:"productoIds,omitempty"`
}

type UpdateInventarioInput struct {
	Cantidad *int    `json:"cantidad,omitempty"`
	Almacen  *string `json:"almacen,omitempty"`
}

type UpdateProductoInput struct {
	Nombre      *string  `json:"nombre,omitempty"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Precio      *float64 `json:"precio,omitempty"`
}
