// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/categoria.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoriaService_CreateCategoria_FullMethodName = "/productos.CategoriaService/CreateCategoria"
	CategoriaService_GetCategoria_FullMethodName    = "/productos.CategoriaService/GetCategoria"
	CategoriaService_UpdateCategoria_FullMethodName = "/productos.CategoriaService/UpdateCategoria"
	CategoriaService_DeleteCategoria_FullMethodName = "/productos.CategoriaService/DeleteCategoria"
	CategoriaService_ListCategorias_FullMethodName  = "/productos.CategoriaService/ListCategorias"
)

// CategoriaServiceClient is the client API for CategoriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoriaServiceClient interface {
	CreateCategoria(ctx context.Context, in *CreateCategoriaRequest, opts ...grpc.CallOption) (*CreateCategoriaResponse, error)
	GetCategoria(ctx context.Context, in *GetCategoriaRequest, opts ...grpc.CallOption) (*GetCategoriaResponse, error)
	UpdateCategoria(ctx context.Context, in *UpdateCategoriaRequest, opts ...grpc.CallOption) (*UpdateCategoriaResponse, error)
	DeleteCategoria(ctx context.Context, in *DeleteCategoriaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListCategorias(ctx context.Context, in *ListCategoriasRequest, opts ...grpc.CallOption) (*ListCategoriasResponse, error)
}

type categoriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoriaServiceClient(cc grpc.ClientConnInterface) CategoriaServiceClient {
	return &categoriaServiceClient{cc}
}

func (c *categoriaServiceClient) CreateCategoria(ctx context.Context, in *CreateCategoriaRequest, opts ...grpc.CallOption) (*CreateCategoriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoriaResponse)
	err := c.cc.Invoke(ctx, CategoriaService_CreateCategoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriaServiceClient) GetCategoria(ctx context.Context, in *GetCategoriaRequest, opts ...grpc.CallOption) (*GetCategoriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriaResponse)
	err := c.cc.Invoke(ctx, CategoriaService_GetCategoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriaServiceClient) UpdateCategoria(ctx context.Context, in *UpdateCategoriaRequest, opts ...grpc.CallOption) (*UpdateCategoriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoriaResponse)
	err := c.cc.Invoke(ctx, CategoriaService_UpdateCategoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriaServiceClient) DeleteCategoria(ctx context.Context, in *DeleteCategoriaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CategoriaService_DeleteCategoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriaServiceClient) ListCategorias(ctx context.Context, in *ListCategoriasRequest, opts ...grpc.CallOption) (*ListCategoriasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriasResponse)
	err := c.cc.Invoke(ctx, CategoriaService_ListCategorias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoriaServiceServer is the server API for CategoriaService service.
// All implementations must embed UnimplementedCategoriaServiceServer
// for forward compatibility.
type CategoriaServiceServer interface {
	CreateCategoria(context.Context, *CreateCategoriaRequest) (*CreateCategoriaResponse, error)
	GetCategoria(context.Context, *GetCategoriaRequest) (*GetCategoriaResponse, error)
	UpdateCategoria(context.Context, *UpdateCategoriaRequest) (*UpdateCategoriaResponse, error)
	DeleteCategoria(context.Context, *DeleteCategoriaRequest) (*emptypb.Empty, error)
	ListCategorias(context.Context, *ListCategoriasRequest) (*ListCategoriasResponse, error)
	mustEmbedUnimplementedCategoriaServiceServer()
}

// UnimplementedCategoriaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoriaServiceServer struct{}

func (UnimplementedCategoriaServiceServer) CreateCategoria(context.Context, *CreateCategoriaRequest) (*CreateCategoriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategoria not implemented")
}
func (UnimplementedCategoriaServiceServer) GetCategoria(context.Context, *GetCategoriaRequest) (*GetCategoriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoria not implemented")
}
func (UnimplementedCategoriaServiceServer) UpdateCategoria(context.Context, *UpdateCategoriaRequest) (*UpdateCategoriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategoria not implemented")
}
func (UnimplementedCategoriaServiceServer) DeleteCategoria(context.Context, *DeleteCategoriaRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategoria not implemented")
}
func (UnimplementedCategoriaServiceServer) ListCategorias(context.Context, *ListCategoriasRequest) (*ListCategoriasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategorias not implemented")
}
func (UnimplementedCategoriaServiceServer) mustEmbedUnimplementedCategoriaServiceServer() {}
func (UnimplementedCategoriaServiceServer) testEmbeddedByValue()                          {}

// UnsafeCategoriaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoriaServiceServer will
// result in compilation errors.
type UnsafeCategoriaServiceServer interface {
	mustEmbedUnimplementedCategoriaServiceServer()
}

func RegisterCategoriaServiceServer(s grpc.ServiceRegistrar, srv CategoriaServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoriaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoriaService_ServiceDesc, srv)
}

func _CategoriaService_CreateCategoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).CreateCategoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_CreateCategoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).CreateCategoria(ctx, req.(*CreateCategoriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriaService_GetCategoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).GetCategoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_GetCategoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).GetCategoria(ctx, req.(*GetCategoriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriaService_UpdateCategoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).UpdateCategoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_UpdateCategoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).UpdateCategoria(ctx, req.(*UpdateCategoriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriaService_DeleteCategoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).DeleteCategoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_DeleteCategoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).DeleteCategoria(ctx, req.(*DeleteCategoriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriaService_ListCategorias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).ListCategorias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_ListCategorias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).ListCategorias(ctx, req.(*ListCategoriasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoriaService_ServiceDesc is the grpc.ServiceDesc for CategoriaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoriaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productos.CategoriaService",
	HandlerType: (*CategoriaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategoria",
			Handler:    _CategoriaService_CreateCategoria_Handler,
		},
		{
			MethodName: "GetCategoria",
			Handler:    _CategoriaService_GetCategoria_Handler,
		},
		{
			MethodName: "UpdateCategoria",
			Handler:    _CategoriaService_UpdateCategoria_Handler,
		},
		{
			MethodName: "DeleteCategoria",
			Handler:    _CategoriaService_DeleteCategoria_Handler,
		},
		{
			MethodName: "ListCategorias",
			Handler:    _CategoriaService_ListCategorias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/categoria.proto",
}
