// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/categoria.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Categoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	ProductoIds   []string               `protobuf:"bytes,4,rep,name=producto_ids,json=productoIds,proto3" json:"producto_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	mi := &file_proto_categoria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{0}
}

func (x *Categoria) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Categoria) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Categoria) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Categoria) GetProductoIds() []string {
	if x != nil {
		return x.ProductoIds
	}
	return nil
}

func (x *Categoria) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Categoria) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCategoriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,2,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	ProductoIds   []string               `protobuf:"bytes,3,rep,name=producto_ids,json=productoIds,proto3" json:"producto_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoriaRequest) Reset() {
	*x = CreateCategoriaRequest{}
	mi := &file_proto_categoria_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoriaRequest) ProtoMessage() {}

func (x *CreateCategoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoriaRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoriaRequest) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoriaRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreateCategoriaRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreateCategoriaRequest) GetProductoIds() []string {
	if x != nil {
		return x.ProductoIds
	}
	return nil
}

type CreateCategoriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categoria     *Categoria             `protobuf:"bytes,1,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoriaResponse) Reset() {
	*x = CreateCategoriaResponse{}
	mi := &file_proto_categoria_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoriaResponse) ProtoMessage() {}

func (x *CreateCategoriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoriaResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoriaResponse) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoriaResponse) GetCategoria() *Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

type GetCategoriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriaRequest) Reset() {
	*x = GetCategoriaRequest{}
	mi := &file_proto_categoria_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriaRequest) ProtoMessage() {}

func (x *GetCategoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriaRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriaRequest) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoriaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCategoriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categoria     *Categoria             `protobuf:"bytes,1,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriaResponse) Reset() {
	*x = GetCategoriaResponse{}
	mi := &file_proto_categoria_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriaResponse) ProtoMessage() {}

func (x *GetCategoriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriaResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriaResponse) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{4}
}

func (x *GetCategoriaResponse) GetCategoria() *Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

type UpdateCategoriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	ProductoIds   []string               `protobuf:"bytes,4,rep,name=producto_ids,json=productoIds,proto3" json:"producto_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoriaRequest) Reset() {
	*x = UpdateCategoriaRequest{}
	mi := &file_proto_categoria_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoriaRequest) ProtoMessage() {}

func (x *UpdateCategoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoriaRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoriaRequest) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCategoriaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoriaRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UpdateCategoriaRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *UpdateCategoriaRequest) GetProductoIds() []string {
	if x != nil {
		return x.ProductoIds
	}
	return nil
}

type UpdateCategoriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categoria     *Categoria             `protobuf:"bytes,1,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoriaResponse) Reset() {
	*x = UpdateCategoriaResponse{}
	mi := &file_proto_categoria_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoriaResponse) ProtoMessage() {}

func (x *UpdateCategoriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoriaResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoriaResponse) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCategoriaResponse) GetCategoria() *Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

type DeleteCategoriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoriaRequest) Reset() {
	*x = DeleteCategoriaRequest{}
	mi := &file_proto_categoria_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoriaRequest) ProtoMessage() {}

func (x *DeleteCategoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoriaRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoriaRequest) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCategoriaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCategoriasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriasRequest) Reset() {
	*x = ListCategoriasRequest{}
	mi := &file_proto_categoria_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriasRequest) ProtoMessage() {}

func (x *ListCategoriasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriasRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriasRequest) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{8}
}

type ListCategoriasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categorias    []*Categoria           `protobuf:"bytes,1,rep,name=categorias,proto3" json:"categorias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriasResponse) Reset() {
	*x = ListCategoriasResponse{}
	mi := &file_proto_categoria_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriasResponse) ProtoMessage() {}

func (x *ListCategoriasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_categoria_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriasResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriasResponse) Descriptor() ([]byte, []int) {
	return file_proto_categoria_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategoriasResponse) GetCategorias() []*Categoria {
	if x != nil {
		return x.Categorias
	}
	return nil
}

var File_proto_categoria_proto protoreflect.FileDescriptor

const file_proto_categoria_proto_rawDesc = "" +
	"\n" +
	"\x15proto/categoria.proto\x12\tproductos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\tCategoria\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12!\n" +
	"\fproducto_ids\x18\x04 \x03(\tR\vproductoIds\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\x16CreateCategoriaRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x02 \x01(\tR\vdescripcion\x12!\n" +
	"\fproducto_ids\x18\x03 \x03(\tR\vproductoIds\"M\n" +
	"\x17CreateCategoriaResponse\x122\n" +
	"\tcategoria\x18\x01 \x01(\v2\x14.productos.CategoriaR\tcategoria\"%\n" +
	"\x13GetCategoriaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14GetCategoriaResponse\x122\n" +
	"\tcategoria\x18\x01 \x01(\v2\x14.productos.CategoriaR\tcategoria\"\x85\x01\n" +
	"\x16UpdateCategoriaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12!\n" +
	"\fproducto_ids\x18\x04 \x03(\tR\vproductoIds\"M\n" +
	"\x17UpdateCategoriaResponse\x122\n" +
	"\tcategoria\x18\x01 \x01(\v2\x14.productos.CategoriaR\tcategoria\"(\n" +
	"\x16DeleteCategoriaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15ListCategoriasRequest\"N\n" +
	"\x16ListCategoriasResponse\x124\n" +
	"\n" +
	"categorias\x18\x01 \x03(\v2\x14.productos.CategoriaR\n" +
	"categorias2\xbc\x03\n" +
	"\x10CategoriaService\x12X\n" +
	"\x0fCreateCategoria\x12!.productos.CreateCategoriaRequest\x1a\".productos.CreateCategoriaResponse\x12O\n" +
	"\fGetCategoria\x12\x1e.productos.GetCategoriaRequest\x1a\x1f.productos.GetCategoriaResponse\x12X\n" +
	"\x0fUpdateCategoria\x12!.productos.UpdateCategoriaRequest\x1a\".productos.UpdateCategoriaResponse\x12L\n" +
	"\x0fDeleteCategoria\x12!.productos.DeleteCategoriaRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x0eListCategorias\x12 .productos.ListCategoriasRequest\x1a!.productos.ListCategoriasResponseB\x1fZ\x1dbackend-productos/proto;protob\x06proto3"

var (
	file_proto_categoria_proto_rawDescOnce sync.Once
	file_proto_categoria_proto_rawDescData []byte
)

func file_proto_categoria_proto_rawDescGZIP() []byte {
	file_proto_categoria_proto_rawDescOnce.Do(func() {
		file_proto_categoria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_categoria_proto_rawDesc), len(file_proto_categoria_proto_rawDesc)))
	})
	return file_proto_categoria_proto_rawDescData
}

var file_proto_categoria_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_categoria_proto_goTypes = []any{
	(*Categoria)(nil),               // 0: productos.Categoria
	(*CreateCategoriaRequest)(nil),  // 1: productos.CreateCategoriaRequest
	(*CreateCategoriaResponse)(nil), // 2: productos.CreateCategoriaResponse
	(*GetCategoriaRequest)(nil),     // 3: productos.GetCategoriaRequest
	(*GetCategoriaResponse)(nil),    // 4: productos.GetCategoriaResponse
	(*UpdateCategoriaRequest)(nil),  // 5: productos.UpdateCategoriaRequest
	(*UpdateCategoriaResponse)(nil), // 6: productos.UpdateCategoriaResponse
	(*DeleteCategoriaRequest)(nil),  // 7: productos.DeleteCategoriaRequest
	(*ListCategoriasRequest)(nil),   // 8: productos.ListCategoriasRequest
	(*ListCategoriasResponse)(nil),  // 9: productos.ListCategoriasResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_proto_categoria_proto_depIdxs = []int32{
	10, // 0: productos.Categoria.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: productos.Categoria.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: productos.CreateCategoriaResponse.categoria:type_name -> productos.Categoria
	0,  // 3: productos.GetCategoriaResponse.categoria:type_name -> productos.Categoria
	0,  // 4: productos.UpdateCategoriaResponse.categoria:type_name -> productos.Categoria
	0,  // 5: productos.ListCategoriasResponse.categorias:type_name -> productos.Categoria
	1,  // 6: productos.CategoriaService.CreateCategoria:input_type -> productos.CreateCategoriaRequest
	3,  // 7: productos.CategoriaService.GetCategoria:input_type -> productos.GetCategoriaRequest
	5,  // 8: productos.CategoriaService.UpdateCategoria:input_type -> productos.UpdateCategoriaRequest
	7,  // 9: productos.CategoriaService.DeleteCategoria:input_type -> productos.DeleteCategoriaRequest
	8,  // 10: productos.CategoriaService.ListCategorias:input_type -> productos.ListCategoriasRequest
	2,  // 11: productos.CategoriaService.CreateCategoria:output_type -> productos.CreateCategoriaResponse
	4,  // 12: productos.CategoriaService.GetCategoria:output_type -> productos.GetCategoriaResponse
	6,  // 13: productos.CategoriaService.UpdateCategoria:output_type -> productos.UpdateCategoriaResponse
	11, // 14: productos.CategoriaService.DeleteCategoria:output_type -> google.protobuf.Empty
	9,  // 15: productos.CategoriaService.ListCategorias:output_type -> productos.ListCategoriasResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_categoria_proto_init() }
func file_proto_categoria_proto_init() {
	if File_proto_categoria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_categoria_proto_rawDesc), len(file_proto_categoria_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_categoria_proto_goTypes,
		DependencyIndexes: file_proto_categoria_proto_depIdxs,
		MessageInfos:      file_proto_categoria_proto_msgTypes,
	}.Build()
	File_proto_categoria_proto = out.File
	file_proto_categoria_proto_goTypes = nil
	file_proto_categoria_proto_depIdxs = nil
}
