// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/inventario.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventarioService_CreateInventario_FullMethodName          = "/productos.InventarioService/CreateInventario"
	InventarioService_GetInventario_FullMethodName             = "/productos.InventarioService/GetInventario"
	InventarioService_GetInventarioByProductoId_FullMethodName = "/productos.InventarioService/GetInventarioByProductoId"
	InventarioService_UpdateInventario_FullMethodName          = "/productos.InventarioService/UpdateInventario"
	InventarioService_DeleteInventario_FullMethodName          = "/productos.InventarioService/DeleteInventario"
	InventarioService_ListInventarios_FullMethodName           = "/productos.InventarioService/ListInventarios"
)

// InventarioServiceClient is the client API for InventarioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventarioServiceClient interface {
	CreateInventario(ctx context.Context, in *CreateInventarioRequest, opts ...grpc.CallOption) (*CreateInventarioResponse, error)
	GetInventario(ctx context.Context, in *GetInventarioRequest, opts ...grpc.CallOption) (*GetInventarioResponse, error)
	GetInventarioByProductoId(ctx context.Context, in *GetInventarioByProductoIdRequest, opts ...grpc.CallOption) (*GetInventarioByProductoIdResponse, error)
	UpdateInventario(ctx context.Context, in *UpdateInventarioRequest, opts ...grpc.CallOption) (*UpdateInventarioResponse, error)
	DeleteInventario(ctx context.Context, in *DeleteInventarioRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListInventarios(ctx context.Context, in *ListInventariosRequest, opts ...grpc.CallOption) (*ListInventariosResponse, error)
}

type inventarioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventarioServiceClient(cc grpc.ClientConnInterface) InventarioServiceClient {
	return &inventarioServiceClient{cc}
}

func (c *inventarioServiceClient) CreateInventario(ctx context.Context, in *CreateInventarioRequest, opts ...grpc.CallOption) (*CreateInventarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInventarioResponse)
	err := c.cc.Invoke(ctx, InventarioService_CreateInventario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarioServiceClient) GetInventario(ctx context.Context, in *GetInventarioRequest, opts ...grpc.CallOption) (*GetInventarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventarioResponse)
	err := c.cc.Invoke(ctx, InventarioService_GetInventario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarioServiceClient) GetInventarioByProductoId(ctx context.Context, in *GetInventarioByProductoIdRequest, opts ...grpc.CallOption) (*GetInventarioByProductoIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventarioByProductoIdResponse)
	err := c.cc.Invoke(ctx, InventarioService_GetInventarioByProductoId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarioServiceClient) UpdateInventario(ctx context.Context, in *UpdateInventarioRequest, opts ...grpc.CallOption) (*UpdateInventarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInventarioResponse)
	err := c.cc.Invoke(ctx, InventarioService_UpdateInventario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarioServiceClient) DeleteInventario(ctx context.Context, in *DeleteInventarioRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InventarioService_DeleteInventario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarioServiceClient) ListInventarios(ctx context.Context, in *ListInventariosRequest, opts ...grpc.CallOption) (*ListInventariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInventariosResponse)
	err := c.cc.Invoke(ctx, InventarioService_ListInventarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventarioServiceServer is the server API for InventarioService service.
// All implementations must embed UnimplementedInventarioServiceServer
// for forward compatibility.
type InventarioServiceServer interface {
	CreateInventario(context.Context, *CreateInventarioRequest) (*CreateInventarioResponse, error)
	GetInventario(context.Context, *GetInventarioRequest) (*GetInventarioResponse, error)
	GetInventarioByProductoId(context.Context, *GetInventarioByProductoIdRequest) (*GetInventarioByProductoIdResponse, error)
	UpdateInventario(context.Context, *UpdateInventarioRequest) (*UpdateInventarioResponse, error)
	DeleteInventario(context.Context, *DeleteInventarioRequest) (*emptypb.Empty, error)
	ListInventarios(context.Context, *ListInventariosRequest) (*ListInventariosResponse, error)
	mustEmbedUnimplementedInventarioServiceServer()
}

// UnimplementedInventarioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventarioServiceServer struct{}

func (UnimplementedInventarioServiceServer) CreateInventario(context.Context, *CreateInventarioRequest) (*CreateInventarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInventario not implemented")
}
func (UnimplementedInventarioServiceServer) GetInventario(context.Context, *GetInventarioRequest) (*GetInventarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventario not implemented")
}
func (UnimplementedInventarioServiceServer) GetInventarioByProductoId(context.Context, *GetInventarioByProductoIdRequest) (*GetInventarioByProductoIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventarioByProductoId not implemented")
}
func (UnimplementedInventarioServiceServer) UpdateInventario(context.Context, *UpdateInventarioRequest) (*UpdateInventarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInventario not implemented")
}
func (UnimplementedInventarioServiceServer) DeleteInventario(context.Context, *DeleteInventarioRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInventario not implemented")
}
func (UnimplementedInventarioServiceServer) ListInventarios(context.Context, *ListInventariosRequest) (*ListInventariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInventarios not implemented")
}
func (UnimplementedInventarioServiceServer) mustEmbedUnimplementedInventarioServiceServer() {}
func (UnimplementedInventarioServiceServer) testEmbeddedByValue()                           {}

// UnsafeInventarioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventarioServiceServer will
// result in compilation errors.
type UnsafeInventarioServiceServer interface {
	mustEmbedUnimplementedInventarioServiceServer()
}

func RegisterInventarioServiceServer(s grpc.ServiceRegistrar, srv InventarioServiceServer) {
	// If the following call panics, it indicates UnimplementedInventarioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventarioService_ServiceDesc, srv)
}

func _InventarioService_CreateInventario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInventarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).CreateInventario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_CreateInventario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).CreateInventario(ctx, req.(*CreateInventarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarioService_GetInventario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).GetInventario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_GetInventario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).GetInventario(ctx, req.(*GetInventarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarioService_GetInventarioByProductoId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventarioByProductoIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).GetInventarioByProductoId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_GetInventarioByProductoId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).GetInventarioByProductoId(ctx, req.(*GetInventarioByProductoIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarioService_UpdateInventario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).UpdateInventario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_UpdateInventario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).UpdateInventario(ctx, req.(*UpdateInventarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarioService_DeleteInventario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInventarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).DeleteInventario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_DeleteInventario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).DeleteInventario(ctx, req.(*DeleteInventarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarioService_ListInventarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInventariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarioServiceServer).ListInventarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarioService_ListInventarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarioServiceServer).ListInventarios(ctx, req.(*ListInventariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventarioService_ServiceDesc is the grpc.ServiceDesc for InventarioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventarioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productos.InventarioService",
	HandlerType: (*InventarioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInventario",
			Handler:    _InventarioService_CreateInventario_Handler,
		},
		{
			MethodName: "GetInventario",
			Handler:    _InventarioService_GetInventario_Handler,
		},
		{
			MethodName: "GetInventarioByProductoId",
			Handler:    _InventarioService_GetInventarioByProductoId_Handler,
		},
		{
			MethodName: "UpdateInventario",
			Handler:    _InventarioService_UpdateInventario_Handler,
		},
		{
			MethodName: "DeleteInventario",
			Handler:    _InventarioService_DeleteInventario_Handler,
		},
		{
			MethodName: "ListInventarios",
			Handler:    _InventarioService_ListInventarios_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventario.proto",
}
