// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventario.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductoId    string                 `protobuf:"bytes,2,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Cantidad      int32                  `protobuf:"varint,3,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Almacen       string                 `protobuf:"bytes,4,opt,name=almacen,proto3" json:"almacen,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventario) Reset() {
	*x = Inventario{}
	mi := &file_proto_inventario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventario) ProtoMessage() {}

func (x *Inventario) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventario.ProtoReflect.Descriptor instead.
func (*Inventario) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{0}
}

func (x *Inventario) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inventario) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *Inventario) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *Inventario) GetAlmacen() string {
	if x != nil {
		return x.Almacen
	}
	return ""
}

func (x *Inventario) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Inventario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateInventarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductoId    string                 `protobuf:"bytes,1,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Cantidad      int32                  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Almacen       string                 `protobuf:"bytes,3,opt,name=almacen,proto3" json:"almacen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventarioRequest) Reset() {
	*x = CreateInventarioRequest{}
	mi := &file_proto_inventario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventarioRequest) ProtoMessage() {}

func (x *CreateInventarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventarioRequest.ProtoReflect.Descriptor instead.
func (*CreateInventarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInventarioRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *CreateInventarioRequest) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *CreateInventarioRequest) GetAlmacen() string {
	if x != nil {
		return x.Almacen
	}
	return ""
}

type CreateInventarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventario    *Inventario            `protobuf:"bytes,1,opt,name=inventario,proto3" json:"inventario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventarioResponse) Reset() {
	*x = CreateInventarioResponse{}
	mi := &file_proto_inventario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventarioResponse) ProtoMessage() {}

func (x *CreateInventarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventarioResponse.ProtoReflect.Descriptor instead.
func (*CreateInventarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInventarioResponse) GetInventario() *Inventario {
	if x != nil {
		return x.Inventario
	}
	return nil
}

type GetInventarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventarioRequest) Reset() {
	*x = GetInventarioRequest{}
	mi := &file_proto_inventario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventarioRequest) ProtoMessage() {}

func (x *GetInventarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventarioRequest.ProtoReflect.Descriptor instead.
func (*GetInventarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInventarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventario    *Inventario            `protobuf:"bytes,1,opt,name=inventario,proto3" json:"inventario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventarioResponse) Reset() {
	*x = GetInventarioResponse{}
	mi := &file_proto_inventario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventarioResponse) ProtoMessage() {}

func (x *GetInventarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventarioResponse.ProtoReflect.Descriptor instead.
func (*GetInventarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{4}
}

func (x *GetInventarioResponse) GetInventario() *Inventario {
	if x != nil {
		return x.Inventario
	}
	return nil
}

type GetInventarioByProductoIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductoId    string                 `protobuf:"bytes,1,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventarioByProductoIdRequest) Reset() {
	*x = GetInventarioByProductoIdRequest{}
	mi := &file_proto_inventario_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventarioByProductoIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventarioByProductoIdRequest) ProtoMessage() {}

func (x *GetInventarioByProductoIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventarioByProductoIdRequest.ProtoReflect.Descriptor instead.
func (*GetInventarioByProductoIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{5}
}

func (x *GetInventarioByProductoIdRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

type GetInventarioByProductoIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventario    *Inventario            `protobuf:"bytes,1,opt,name=inventario,proto3" json:"inventario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventarioByProductoIdResponse) Reset() {
	*x = GetInventarioByProductoIdResponse{}
	mi := &file_proto_inventario_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventarioByProductoIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventarioByProductoIdResponse) ProtoMessage() {}

func (x *GetInventarioByProductoIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventarioByProductoIdResponse.ProtoReflect.Descriptor instead.
func (*GetInventarioByProductoIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{6}
}

func (x *GetInventarioByProductoIdResponse) GetInventario() *Inventario {
	if x != nil {
		return x.Inventario
	}
	return nil
}

type UpdateInventarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductoId    string                 `protobuf:"bytes,2,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Cantidad      int32                  `protobuf:"varint,3,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Almacen       string                 `protobuf:"bytes,4,opt,name=almacen,proto3" json:"almacen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventarioRequest) Reset() {
	*x = UpdateInventarioRequest{}
	mi := &file_proto_inventario_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventarioRequest) ProtoMessage() {}

func (x *UpdateInventarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventarioRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInventarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInventarioRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *UpdateInventarioRequest) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *UpdateInventarioRequest) GetAlmacen() string {
	if x != nil {
		return x.Almacen
	}
	return ""
}

type UpdateInventarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventario    *Inventario            `protobuf:"bytes,1,opt,name=inventario,proto3" json:"inventario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventarioResponse) Reset() {
	*x = UpdateInventarioResponse{}
	mi := &file_proto_inventario_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventarioResponse) ProtoMessage() {}

func (x *UpdateInventarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventarioResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInventarioResponse) GetInventario() *Inventario {
	if x != nil {
		return x.Inventario
	}
	return nil
}

type DeleteInventarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventarioRequest) Reset() {
	*x = DeleteInventarioRequest{}
	mi := &file_proto_inventario_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventarioRequest) ProtoMessage() {}

func (x *DeleteInventarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventarioRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInventarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListInventariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventariosRequest) Reset() {
	*x = ListInventariosRequest{}
	mi := &file_proto_inventario_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventariosRequest) ProtoMessage() {}

func (x *ListInventariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventariosRequest.ProtoReflect.Descriptor instead.
func (*ListInventariosRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{10}
}

type ListInventariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventarios   []*Inventario          `protobuf:"bytes,1,rep,name=inventarios,proto3" json:"inventarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventariosResponse) Reset() {
	*x = ListInventariosResponse{}
	mi := &file_proto_inventario_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventariosResponse) ProtoMessage() {}

func (x *ListInventariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventario_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventariosResponse.ProtoReflect.Descriptor instead.
func (*ListInventariosResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventario_proto_rawDescGZIP(), []int{11}
}

func (x *ListInventariosResponse) GetInventarios() []*Inventario {
	if x != nil {
		return x.Inventarios
	}
	return nil
}

var File_proto_inventario_proto protoreflect.FileDescriptor

const file_proto_inventario_proto_rawDesc = "" +
	"\n" +
	"\x16proto/inventario.proto\x12\tproductos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\n" +
	"Inventario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vproducto_id\x18\x02 \x01(\tR\n" +
	"productoId\x12\x1a\n" +
	"\bcantidad\x18\x03 \x01(\x05R\bcantidad\x12\x18\n" +
	"\aalmacen\x18\x04 \x01(\tR\aalmacen\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"p\n" +
	"\x17CreateInventarioRequest\x12\x1f\n" +
	"\vproducto_id\x18\x01 \x01(\tR\n" +
	"productoId\x12\x1a\n" +
	"\bcantidad\x18\x02 \x01(\x05R\bcantidad\x12\x18\n" +
	"\aalmacen\x18\x03 \x01(\tR\aalmacen\"Q\n" +
	"\x18CreateInventarioResponse\x125\n" +
	"\n" +
	"inventario\x18\x01 \x01(\v2\x15.productos.InventarioR\n" +
	"inventario\"&\n" +
	"\x14GetInventarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x15GetInventarioResponse\x125\n" +
	"\n" +
	"inventario\x18\x01 \x01(\v2\x15.productos.InventarioR\n" +
	"inventario\"C\n" +
	" GetInventarioByProductoIdRequest\x12\x1f\n" +
	"\vproducto_id\x18\x01 \x01(\tR\n" +
	"productoId\"Z\n" +
	"!GetInventarioByProductoIdResponse\x125\n" +
	"\n" +
	"inventario\x18\x01 \x01(\v2\x15.productos.InventarioR\n" +
	"inventario\"\x80\x01\n" +
	"\x17UpdateInventarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vproducto_id\x18\x02 \x01(\tR\n" +
	"productoId\x12\x1a\n" +
	"\bcantidad\x18\x03 \x01(\x05R\bcantidad\x12\x18\n" +
	"\aalmacen\x18\x04 \x01(\tR\aalmacen\"Q\n" +
	"\x18UpdateInventarioResponse\x125\n" +
	"\n" +
	"inventario\x18\x01 \x01(\v2\x15.productos.InventarioR\n" +
	"inventario\")\n" +
	"\x17DeleteInventarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ListInventariosRequest\"R\n" +
	"\x17ListInventariosResponse\x127\n" +
	"\vinventarios\x18\x01 \x03(\v2\x15.productos.InventarioR\vinventarios2\xc3\x04\n" +
	"\x11InventarioService\x12[\n" +
	"\x10CreateInventario\x12\".productos.CreateInventarioRequest\x1a#.productos.CreateInventarioResponse\x12R\n" +
	"\rGetInventario\x12\x1f.productos.GetInventarioRequest\x1a .productos.GetInventarioResponse\x12v\n" +
	"\x19GetInventarioByProductoId\x12+.productos.GetInventarioByProductoIdRequest\x1a,.productos.GetInventarioByProductoIdResponse\x12[\n" +
	"\x10UpdateInventario\x12\".productos.UpdateInventarioRequest\x1a#.productos.UpdateInventarioResponse\x12N\n" +
	"\x10DeleteInventario\x12\".productos.DeleteInventarioRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x0fListInventarios\x12!.productos.ListInventariosRequest\x1a\".productos.ListInventariosResponseB\x1fZ\x1dbackend-productos/proto;protob\x06proto3"

var (
	file_proto_inventario_proto_rawDescOnce sync.Once
	file_proto_inventario_proto_rawDescData []byte
)

func file_proto_inventario_proto_rawDescGZIP() []byte {
	file_proto_inventario_proto_rawDescOnce.Do(func() {
		file_proto_inventario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventario_proto_rawDesc), len(file_proto_inventario_proto_rawDesc)))
	})
	return file_proto_inventario_proto_rawDescData
}

var file_proto_inventario_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_inventario_proto_goTypes = []any{
	(*Inventario)(nil),                        // 0: productos.Inventario
	(*CreateInventarioRequest)(nil),           // 1: productos.CreateInventarioRequest
	(*CreateInventarioResponse)(nil),          // 2: productos.CreateInventarioResponse
	(*GetInventarioRequest)(nil),              // 3: productos.GetInventarioRequest
	(*GetInventarioResponse)(nil),             // 4: productos.GetInventarioResponse
	(*GetInventarioByProductoIdRequest)(nil),  // 5: productos.GetInventarioByProductoIdRequest
	(*GetInventarioByProductoIdResponse)(nil), // 6: productos.GetInventarioByProductoIdResponse
	(*UpdateInventarioRequest)(nil),           // 7: productos.UpdateInventarioRequest
	(*UpdateInventarioResponse)(nil),          // 8: productos.UpdateInventarioResponse
	(*DeleteInventarioRequest)(nil),           // 9: productos.DeleteInventarioRequest
	(*ListInventariosRequest)(nil),            // 10: productos.ListInventariosRequest
	(*ListInventariosResponse)(nil),           // 11: productos.ListInventariosResponse
	(*timestamppb.Timestamp)(nil),             // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 13: google.protobuf.Empty
}
var file_proto_inventario_proto_depIdxs = []int32{
	12, // 0: productos.Inventario.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: productos.Inventario.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: productos.CreateInventarioResponse.inventario:type_name -> productos.Inventario
	0,  // 3: productos.GetInventarioResponse.inventario:type_name -> productos.Inventario
	0,  // 4: productos.GetInventarioByProductoIdResponse.inventario:type_name -> productos.Inventario
	0,  // 5: productos.UpdateInventarioResponse.inventario:type_name -> productos.Inventario
	0,  // 6: productos.ListInventariosResponse.inventarios:type_name -> productos.Inventario
	1,  // 7: productos.InventarioService.CreateInventario:input_type -> productos.CreateInventarioRequest
	3,  // 8: productos.InventarioService.GetInventario:input_type -> productos.GetInventarioRequest
	5,  // 9: productos.InventarioService.GetInventarioByProductoId:input_type -> productos.GetInventarioByProductoIdRequest
	7,  // 10: productos.InventarioService.UpdateInventario:input_type -> productos.UpdateInventarioRequest
	9,  // 11: productos.InventarioService.DeleteInventario:input_type -> productos.DeleteInventarioRequest
	10, // 12: productos.InventarioService.ListInventarios:input_type -> productos.ListInventariosRequest
	2,  // 13: productos.InventarioService.CreateInventario:output_type -> productos.CreateInventarioResponse
	4,  // 14: productos.InventarioService.GetInventario:output_type -> productos.GetInventarioResponse
	6,  // 15: productos.InventarioService.GetInventarioByProductoId:output_type -> productos.GetInventarioByProductoIdResponse
	8,  // 16: productos.InventarioService.UpdateInventario:output_type -> productos.UpdateInventarioResponse
	13, // 17: productos.InventarioService.DeleteInventario:output_type -> google.protobuf.Empty
	11, // 18: productos.InventarioService.ListInventarios:output_type -> productos.ListInventariosResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_inventario_proto_init() }
func file_proto_inventario_proto_init() {
	if File_proto_inventario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventario_proto_rawDesc), len(file_proto_inventario_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventario_proto_goTypes,
		DependencyIndexes: file_proto_inventario_proto_depIdxs,
		MessageInfos:      file_proto_inventario_proto_msgTypes,
	}.Build()
	File_proto_inventario_proto = out.File
	file_proto_inventario_proto_goTypes = nil
	file_proto_inventario_proto_depIdxs = nil
}
