// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/producto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductoService_CreateProducto_FullMethodName = "/productos.ProductoService/CreateProducto"
	ProductoService_GetProducto_FullMethodName    = "/productos.ProductoService/GetProducto"
	ProductoService_UpdateProducto_FullMethodName = "/productos.ProductoService/UpdateProducto"
	ProductoService_DeleteProducto_FullMethodName = "/productos.ProductoService/DeleteProducto"
	ProductoService_ListProductos_FullMethodName  = "/productos.ProductoService/ListProductos"
)

// ProductoServiceClient is the client API for ProductoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductoServiceClient interface {
	CreateProducto(ctx context.Context, in *CreateProductoRequest, opts ...grpc.CallOption) (*CreateProductoResponse, error)
	GetProducto(ctx context.Context, in *GetProductoRequest, opts ...grpc.CallOption) (*GetProductoResponse, error)
	UpdateProducto(ctx context.Context, in *UpdateProductoRequest, opts ...grpc.CallOption) (*UpdateProductoResponse, error)
	DeleteProducto(ctx context.Context, in *DeleteProductoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListProductos(ctx context.Context, in *ListProductosRequest, opts ...grpc.CallOption) (*ListProductosResponse, error)
}

type productoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductoServiceClient(cc grpc.ClientConnInterface) ProductoServiceClient {
	return &productoServiceClient{cc}
}

func (c *productoServiceClient) CreateProducto(ctx context.Context, in *CreateProductoRequest, opts ...grpc.CallOption) (*CreateProductoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductoResponse)
	err := c.cc.Invoke(ctx, ProductoService_CreateProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productoServiceClient) GetProducto(ctx context.Context, in *GetProductoRequest, opts ...grpc.CallOption) (*GetProductoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductoResponse)
	err := c.cc.Invoke(ctx, ProductoService_GetProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productoServiceClient) UpdateProducto(ctx context.Context, in *UpdateProductoRequest, opts ...grpc.CallOption) (*UpdateProductoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductoResponse)
	err := c.cc.Invoke(ctx, ProductoService_UpdateProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productoServiceClient) DeleteProducto(ctx context.Context, in *DeleteProductoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductoService_DeleteProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productoServiceClient) ListProductos(ctx context.Context, in *ListProductosRequest, opts ...grpc.CallOption) (*ListProductosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductosResponse)
	err := c.cc.Invoke(ctx, ProductoService_ListProductos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductoServiceServer is the server API for ProductoService service.
// All implementations must embed UnimplementedProductoServiceServer
// for forward compatibility.
type ProductoServiceServer interface {
	CreateProducto(context.Context, *CreateProductoRequest) (*CreateProductoResponse, error)
	GetProducto(context.Context, *GetProductoRequest) (*GetProductoResponse, error)
	UpdateProducto(context.Context, *UpdateProductoRequest) (*UpdateProductoResponse, error)
	DeleteProducto(context.Context, *DeleteProductoRequest) (*emptypb.Empty, error)
	ListProductos(context.Context, *ListProductosRequest) (*ListProductosResponse, error)
	mustEmbedUnimplementedProductoServiceServer()
}

// UnimplementedProductoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductoServiceServer struct{}

func (UnimplementedProductoServiceServer) CreateProducto(context.Context, *CreateProductoRequest) (*CreateProductoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProducto not implemented")
}
func (UnimplementedProductoServiceServer) GetProducto(context.Context, *GetProductoRequest) (*GetProductoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProducto not implemented")
}
func (UnimplementedProductoServiceServer) UpdateProducto(context.Context, *UpdateProductoRequest) (*UpdateProductoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProducto not implemented")
}
func (UnimplementedProductoServiceServer) DeleteProducto(context.Context, *DeleteProductoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProducto not implemented")
}
func (UnimplementedProductoServiceServer) ListProductos(context.Context, *ListProductosRequest) (*ListProductosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductos not implemented")
}
func (UnimplementedProductoServiceServer) mustEmbedUnimplementedProductoServiceServer() {}
func (UnimplementedProductoServiceServer) testEmbeddedByValue()                         {}

// UnsafeProductoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductoServiceServer will
// result in compilation errors.
type UnsafeProductoServiceServer interface {
	mustEmbedUnimplementedProductoServiceServer()
}

func RegisterProductoServiceServer(s grpc.ServiceRegistrar, srv ProductoServiceServer) {
	// If the following call panics, it indicates UnimplementedProductoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductoService_ServiceDesc, srv)
}

func _ProductoService_CreateProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoServiceServer).CreateProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductoService_CreateProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoServiceServer).CreateProducto(ctx, req.(*CreateProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductoService_GetProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoServiceServer).GetProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductoService_GetProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoServiceServer).GetProducto(ctx, req.(*GetProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductoService_UpdateProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoServiceServer).UpdateProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductoService_UpdateProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoServiceServer).UpdateProducto(ctx, req.(*UpdateProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductoService_DeleteProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoServiceServer).DeleteProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductoService_DeleteProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoServiceServer).DeleteProducto(ctx, req.(*DeleteProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductoService_ListProductos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoServiceServer).ListProductos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductoService_ListProductos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoServiceServer).ListProductos(ctx, req.(*ListProductosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductoService_ServiceDesc is the grpc.ServiceDesc for ProductoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productos.ProductoService",
	HandlerType: (*ProductoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProducto",
			Handler:    _ProductoService_CreateProducto_Handler,
		},
		{
			MethodName: "GetProducto",
			Handler:    _ProductoService_GetProducto_Handler,
		},
		{
			MethodName: "UpdateProducto",
			Handler:    _ProductoService_UpdateProducto_Handler,
		},
		{
			MethodName: "DeleteProducto",
			Handler:    _ProductoService_DeleteProducto_Handler,
		},
		{
			MethodName: "ListProductos",
			Handler:    _ProductoService_ListProductos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/producto.proto",
}
