// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/producto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Producto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,4,opt,name=precio,proto3" json:"precio,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producto) Reset() {
	*x = Producto{}
	mi := &file_proto_producto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producto) ProtoMessage() {}

func (x *Producto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producto.ProtoReflect.Descriptor instead.
func (*Producto) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{0}
}

func (x *Producto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Producto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Producto) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Producto) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Producto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Producto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,2,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,3,opt,name=precio,proto3" json:"precio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductoRequest) Reset() {
	*x = CreateProductoRequest{}
	mi := &file_proto_producto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductoRequest) ProtoMessage() {}

func (x *CreateProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductoRequest.ProtoReflect.Descriptor instead.
func (*CreateProductoRequest) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreateProductoRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreateProductoRequest) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

type CreateProductoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producto      *Producto              `protobuf:"bytes,1,opt,name=producto,proto3" json:"producto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductoResponse) Reset() {
	*x = CreateProductoResponse{}
	mi := &file_proto_producto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductoResponse) ProtoMessage() {}

func (x *CreateProductoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductoResponse.ProtoReflect.Descriptor instead.
func (*CreateProductoResponse) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductoResponse) GetProducto() *Producto {
	if x != nil {
		return x.Producto
	}
	return nil
}

type GetProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductoRequest) Reset() {
	*x = GetProductoRequest{}
	mi := &file_proto_producto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductoRequest) ProtoMessage() {}

func (x *GetProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductoRequest.ProtoReflect.Descriptor instead.
func (*GetProductoRequest) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producto      *Producto              `protobuf:"bytes,1,opt,name=producto,proto3" json:"producto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductoResponse) Reset() {
	*x = GetProductoResponse{}
	mi := &file_proto_producto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductoResponse) ProtoMessage() {}

func (x *GetProductoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductoResponse.ProtoReflect.Descriptor instead.
func (*GetProductoResponse) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductoResponse) GetProducto() *Producto {
	if x != nil {
		return x.Producto
	}
	return nil
}

type UpdateProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,4,opt,name=precio,proto3" json:"precio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductoRequest) Reset() {
	*x = UpdateProductoRequest{}
	mi := &file_proto_producto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductoRequest) ProtoMessage() {}

func (x *UpdateProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductoRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductoRequest) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UpdateProductoRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *UpdateProductoRequest) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

type UpdateProductoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producto      *Producto              `protobuf:"bytes,1,opt,name=producto,proto3" json:"producto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductoResponse) Reset() {
	*x = UpdateProductoResponse{}
	mi := &file_proto_producto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductoResponse) ProtoMessage() {}

func (x *UpdateProductoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductoResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductoResponse) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductoResponse) GetProducto() *Producto {
	if x != nil {
		return x.Producto
	}
	return nil
}

type DeleteProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductoRequest) Reset() {
	*x = DeleteProductoRequest{}
	mi := &file_proto_producto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductoRequest) ProtoMessage() {}

func (x *DeleteProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductoRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductoRequest) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProductosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductosRequest) Reset() {
	*x = ListProductosRequest{}
	mi := &file_proto_producto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductosRequest) ProtoMessage() {}

func (x *ListProductosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductosRequest.ProtoReflect.Descriptor instead.
func (*ListProductosRequest) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Productos     []*Producto            `protobuf:"bytes,1,rep,name=productos,proto3" json:"productos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductosResponse) Reset() {
	*x = ListProductosResponse{}
	mi := &file_proto_producto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductosResponse) ProtoMessage() {}

func (x *ListProductosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductosResponse.ProtoReflect.Descriptor instead.
func (*ListProductosResponse) Descriptor() ([]byte, []int) {
	return file_proto_producto_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductosResponse) GetProductos() []*Producto {
	if x != nil {
		return x.Productos
	}
	return nil
}

var File_proto_producto_proto protoreflect.FileDescriptor

const file_proto_producto_proto_rawDesc = "" +
	"\n" +
	"\x14proto/producto.proto\x12\tproductos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\bProducto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x04 \x01(\x01R\x06precio\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"i\n" +
	"\x15CreateProductoRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x02 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x03 \x01(\x01R\x06precio\"I\n" +
	"\x16CreateProductoResponse\x12/\n" +
	"\bproducto\x18\x01 \x01(\v2\x13.productos.ProductoR\bproducto\"$\n" +
	"\x12GetProductoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13GetProductoResponse\x12/\n" +
	"\bproducto\x18\x01 \x01(\v2\x13.productos.ProductoR\bproducto\"y\n" +
	"\x15UpdateProductoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x04 \x01(\x01R\x06precio\"I\n" +
	"\x16UpdateProductoResponse\x12/\n" +
	"\bproducto\x18\x01 \x01(\v2\x13.productos.ProductoR\bproducto\"'\n" +
	"\x15DeleteProductoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x14ListProductosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x15ListProductosResponse\x121\n" +
	"\tproductos\x18\x01 \x03(\v2\x13.productos.ProductoR\tproductos2\xad\x03\n" +
	"\x0fProductoService\x12U\n" +
	"\x0eCreateProducto\x12 .productos.CreateProductoRequest\x1a!.productos.CreateProductoResponse\x12L\n" +
	"\vGetProducto\x12\x1d.productos.GetProductoRequest\x1a\x1e.productos.GetProductoResponse\x12U\n" +
	"\x0eUpdateProducto\x12 .productos.UpdateProductoRequest\x1a!.productos.UpdateProductoResponse\x12J\n" +
	"\x0eDeleteProducto\x12 .productos.DeleteProductoRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\rListProductos\x12\x1f.productos.ListProductosRequest\x1a .productos.ListProductosResponseB\x1fZ\x1dbackend-productos/proto;protob\x06proto3"

var (
	file_proto_producto_proto_rawDescOnce sync.Once
	file_proto_producto_proto_rawDescData []byte
)

func file_proto_producto_proto_rawDescGZIP() []byte {
	file_proto_producto_proto_rawDescOnce.Do(func() {
		file_proto_producto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_producto_proto_rawDesc), len(file_proto_producto_proto_rawDesc)))
	})
	return file_proto_producto_proto_rawDescData
}

var file_proto_producto_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_producto_proto_goTypes = []any{
	(*Producto)(nil),               // 0: productos.Producto
	(*CreateProductoRequest)(nil),  // 1: productos.CreateProductoRequest
	(*CreateProductoResponse)(nil), // 2: productos.CreateProductoResponse
	(*GetProductoRequest)(nil),     // 3: productos.GetProductoRequest
	(*GetProductoResponse)(nil),    // 4: productos.GetProductoResponse
	(*UpdateProductoRequest)(nil),  // 5: productos.UpdateProductoRequest
	(*UpdateProductoResponse)(nil), // 6: productos.UpdateProductoResponse
	(*DeleteProductoRequest)(nil),  // 7: productos.DeleteProductoRequest
	(*ListProductosRequest)(nil),   // 8: productos.ListProductosRequest
	(*ListProductosResponse)(nil),  // 9: productos.ListProductosResponse
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_proto_producto_proto_depIdxs = []int32{
	10, // 0: productos.Producto.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: productos.Producto.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: productos.CreateProductoResponse.producto:type_name -> productos.Producto
	0,  // 3: productos.GetProductoResponse.producto:type_name -> productos.Producto
	0,  // 4: productos.UpdateProductoResponse.producto:type_name -> productos.Producto
	0,  // 5: productos.ListProductosResponse.productos:type_name -> productos.Producto
	1,  // 6: productos.ProductoService.CreateProducto:input_type -> productos.CreateProductoRequest
	3,  // 7: productos.ProductoService.GetProducto:input_type -> productos.GetProductoRequest
	5,  // 8: productos.ProductoService.UpdateProducto:input_type -> productos.UpdateProductoRequest
	7,  // 9: productos.ProductoService.DeleteProducto:input_type -> productos.DeleteProductoRequest
	8,  // 10: productos.ProductoService.ListProductos:input_type -> productos.ListProductosRequest
	2,  // 11: productos.ProductoService.CreateProducto:output_type -> productos.CreateProductoResponse
	4,  // 12: productos.ProductoService.GetProducto:output_type -> productos.GetProductoResponse
	6,  // 13: productos.ProductoService.UpdateProducto:output_type -> productos.UpdateProductoResponse
	11, // 14: productos.ProductoService.DeleteProducto:output_type -> google.protobuf.Empty
	9,  // 15: productos.ProductoService.ListProductos:output_type -> productos.ListProductosResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_producto_proto_init() }
func file_proto_producto_proto_init() {
	if File_proto_producto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_producto_proto_rawDesc), len(file_proto_producto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_producto_proto_goTypes,
		DependencyIndexes: file_proto_producto_proto_depIdxs,
		MessageInfos:      file_proto_producto_proto_msgTypes,
	}.Build()
	File_proto_producto_proto = out.File
	file_proto_producto_proto_goTypes = nil
	file_proto_producto_proto_depIdxs = nil
}
